# Generated by Django 5.0.3 on 2024-03-08 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('usuario', models.CharField(max_length=25)),
                ('clave', models.CharField(max_length=25)),
                ('estado', models.CharField(max_length=25)),
                ('nivel', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('cuerpo', models.CharField(max_length=3000)),
                ('imagen', models.CharField(max_length=200)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pagina_cms.grupos')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pagina_cms.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('visible', models.CharField(default='NO', max_length=2)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pagina_cms.noticias')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pagina_cms.usuarios')),
            ],
        ),
    ]
